version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: h2
      KEYCLOAK_ADMIN: admin       # Yönetici kullanıcı adı
      KEYCLOAK_ADMIN_PASSWORD: admin123 # Yönetici şifresi
    command: ["start-dev"]
    ports:
      - "8080:8080"
